# Generated by Django 4.1.1 on 2022-09-17 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='number_1',
            field=models.CharField(help_text='Phone number 1', max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='number_2',
            field=models.CharField(blank=True, help_text='Phone number 2', max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
