# Generated by Django 4.1.1 on 2022-09-17 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_alter_retailer_number_1_alter_retailer_number_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='number_2',
            field=models.CharField(blank=True, help_text='Phone number 2', max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
